<?xml version="1.0" encoding="utf-8"?><Database Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="" Member="Class1">
    <Type Name="Class1">
      <Column Member="Property1" Type="System.String" CanBeNull="false" />
      <Column Member="Property2" Type="System.String" CanBeNull="false" />
      <Column Member="Property3" Type="System.String" CanBeNull="false" />
    </Type>
  </Table>
</Database>